name: Stock Data Scraper

on:
  schedule:
    - cron: '0 2 * * 1-5'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twstock pandas
        pip list  # 列出所有安裝的包
    
    - name: Run scraper
      run: |
        python -V  # 輸出 Python 版本
        ls -la  # 列出當前目錄內容
        cat tw_stock_go.py  # 顯示腳本內容
        python tw_stock_go.py
      
    - name: Check data directory
      if: always()
      run: |
        ls -la data || echo "data directory does not exist"
        
    - name: Commit and push if changed
      if: success()
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git add data
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update stock data" && git push)
