name: Stock Data Scraper

on:
  schedule:
    - cron: '0 2 * * 1-5'  # 在工作日（週一到週五）的每天凌晨2點運行
  workflow_dispatch:  # 允許手動觸發

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 明確給予寫入權限
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install twstock pandas lxml
        pip list  # 列出所有安裝的包
    
    - name: Run scraper
      run: |
        python -V  # 輸出 Python 版本
        echo "Current working directory:"
        pwd
        echo "Content of current directory:"
        ls -la
        echo "Content of tw_stock_go.py:"
        cat tw_stock_go.py
        echo "Running tw_stock_go.py:"
        python tw_stock_go.py
      continue-on-error: true
    
    - name: Check file system after scraping
      if: always()
      run: |
        echo "Root directory contents after scraping:"
        ls -la
        echo "Data directory contents (if exists):"
        ls -la data || echo "data directory does not exist"
        echo "Content of data files (if exist):"
        cat data/*.csv data/*.txt || echo "No data files found"
    
    - name: Display Python error
      if: failure()
      run: |
        echo "Last 20 lines of error output:"
        python tw_stock_go.py 2>&1 | tail -n 20
    
    - name: Commit and push if changed
      run: |
        git config --global user.email "action@github.com"
        git config --global user.name "GitHub Action"
        git status
        git add -A
        git diff --staged --quiet || (git commit -m "Update stock data" && git push) || echo "No changes to commit"
    
    - name: Verify push results
      run: |
        echo "Current branch:"
        git branch --show-current
        echo "Latest commit:"
        git log -1
        echo "Remote branches:"
        git branch -r
